export const metadata = {
  title: 'Profile',
  description: 'Generated by create next app',
}

export default function ProfileLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}